import type {
  AppSection,
  BalanceSummary,
  CategorySummary,
  Movement,
  NavigationItem,
  PersonalSection,
  SavingsSection,
  SectionDetail,
  TripSection,
} from '../types/finance'

export const navigationItems: NavigationItem[] = [
  { id: 'summary', label: 'Resumen', icon: 'dashboard', tone: 'info' },
  { id: 'marcos', label: 'Marcos', icon: 'user', tone: 'income' },
  { id: 'nayeli', label: 'Nayeli', icon: 'user', tone: 'expense' },
  { id: 'trip', label: 'Viaje', icon: 'plane', tone: 'info' },
  { id: 'savings', label: 'Ahorros', icon: 'piggy', tone: 'savings' },
  { id: 'gym', label: 'Gym', icon: 'dumbbell', tone: 'info' },
]

export const overviewBalances: BalanceSummary[] = [
  {
    label: 'Saldo Marcos',
    amount: 'S/ 4,820.00',
    description: 'Disponible personal',
    icon: 'user',
    tone: 'income',
  },
  {
    label: 'Saldo Nayeli',
    amount: 'S/ 3,410.50',
    description: 'Disponible personal',
    icon: 'user',
    tone: 'expense',
  },
  {
    label: 'Saldo Viaje',
    amount: 'S/ 1,950.00',
    description: 'Fondo planificado',
    icon: 'plane',
    tone: 'info',
  },
  {
    label: 'Ahorros Soles',
    amount: 'S/ 8,200.00',
    description: 'Meta principal',
    icon: 'piggy',
    tone: 'savings',
  },
  {
    label: 'Ahorros Dólares',
    amount: '$ 1,240.00',
    description: 'Reserva USD',
    icon: 'usd',
    tone: 'savings',
  },
]

export const personalSections: Record<'marcos' | 'nayeli', PersonalSection> = {
  marcos: {
    id: 'marcos',
    name: 'Marcos',
    balance: 'S/ 4,820.00',
    income: 'S/ 3,680.00',
    expenses: 'S/ 1,240.00',
    monthlyBalance: 'S/ 2,440.00',
    metrics: [
      {
        label: 'Saldo actual',
        amount: 'S/ 4,820.00',
        description: 'Disponible para el mes',
        icon: 'wallet',
        tone: 'income',
      },
      {
        label: 'Ingresos del mes',
        amount: 'S/ 3,680.00',
        description: 'Sueldo y extras',
        icon: 'income',
        tone: 'income',
      },
      {
        label: 'Gastos del mes',
        amount: 'S/ 1,240.00',
        description: 'Consumo personal',
        icon: 'expense',
        tone: 'expense',
      },
      {
        label: 'Balance',
        amount: 'S/ 2,440.00',
        description: 'Resultado mensual',
        icon: 'equal',
        tone: 'info',
      },
    ],
    movements: [
      {
        id: 'marcos-1',
        title: 'Sueldo mensual',
        subtitle: 'Trabajo · 25 junio',
        amount: 'S/ 3,200.00',
        icon: 'briefcase',
        kind: 'salary',
        scope: 'marcos',
        tone: 'income',
        date: '2026-06-25',
      },
      {
        id: 'marcos-2',
        title: 'Ingreso extra',
        subtitle: 'Freelance · 21 junio',
        amount: 'S/ 480.00',
        icon: 'income',
        kind: 'income',
        scope: 'marcos',
        tone: 'income',
        date: '2026-06-21',
      },
      {
        id: 'marcos-3',
        title: 'Transporte',
        subtitle: 'Movilidad · 18 junio',
        amount: 'S/ 96.00',
        icon: 'car',
        kind: 'expense',
        scope: 'marcos',
        tone: 'expense',
        date: '2026-06-18',
      },
      {
        id: 'marcos-4',
        title: 'Almuerzos',
        subtitle: 'Comida · 15 junio',
        amount: 'S/ 164.00',
        icon: 'utensils',
        kind: 'expense',
        scope: 'marcos',
        tone: 'expense',
        date: '2026-06-15',
      },
    ],
  },
  nayeli: {
    id: 'nayeli',
    name: 'Nayeli',
    balance: 'S/ 3,410.50',
    income: 'S/ 2,950.00',
    expenses: 'S/ 1,180.90',
    monthlyBalance: 'S/ 1,769.10',
    metrics: [
      {
        label: 'Saldo actual',
        amount: 'S/ 3,410.50',
        description: 'Disponible para el mes',
        icon: 'wallet',
        tone: 'info',
      },
      {
        label: 'Ingresos del mes',
        amount: 'S/ 2,950.00',
        description: 'Ingresos personales',
        icon: 'income',
        tone: 'income',
      },
      {
        label: 'Gastos del mes',
        amount: 'S/ 1,180.90',
        description: 'Gastos registrados',
        icon: 'expense',
        tone: 'expense',
      },
      {
        label: 'Balance',
        amount: 'S/ 1,769.10',
        description: 'Resultado mensual',
        icon: 'equal',
        tone: 'savings',
      },
    ],
    movements: [
      {
        id: 'nayeli-1',
        title: 'Ingreso mensual',
        subtitle: 'Trabajo · 25 junio',
        amount: 'S/ 2,950.00',
        icon: 'briefcase',
        kind: 'income',
        scope: 'nayeli',
        tone: 'income',
        date: '2026-06-25',
      },
      {
        id: 'nayeli-2',
        title: 'Supermercado',
        subtitle: 'Hogar · 22 junio',
        amount: 'S/ 180.90',
        icon: 'shopping',
        kind: 'expense',
        scope: 'nayeli',
        tone: 'expense',
        date: '2026-06-22',
      },
      {
        id: 'nayeli-3',
        title: 'Farmacia',
        subtitle: 'Salud · 17 junio',
        amount: 'S/ 74.50',
        icon: 'health',
        kind: 'expense',
        scope: 'nayeli',
        tone: 'expense',
        date: '2026-06-17',
      },
      {
        id: 'nayeli-4',
        title: 'Venta puntual',
        subtitle: 'Extra · 13 junio',
        amount: 'S/ 220.00',
        icon: 'income',
        kind: 'income',
        scope: 'nayeli',
        tone: 'income',
        date: '2026-06-13',
      },
    ],
  },
}

export const tripSection: TripSection = {
  balance: 'S/ 1,950.00',
  income: 'S/ 2,800.00',
  expenses: 'S/ 850.00',
  available: 'S/ 1,950.00',
  metrics: [
    {
      label: 'Saldo del viaje',
      amount: 'S/ 1,950.00',
      description: 'Fondo actual',
      icon: 'plane',
      tone: 'info',
    },
    {
      label: 'Ingresos',
      amount: 'S/ 2,800.00',
      description: 'Aportes registrados',
      icon: 'income',
      tone: 'income',
    },
    {
      label: 'Gastos',
      amount: 'S/ 850.00',
      description: 'Reservas y compras',
      icon: 'expense',
      tone: 'expense',
    },
    {
      label: 'Disponible',
      amount: 'S/ 1,950.00',
      description: 'Listo para usar',
      icon: 'equal',
      tone: 'savings',
    },
  ],
  latestExpenses: [
    {
      id: 'trip-1',
      title: 'Reserva hotel',
      subtitle: 'Hospedaje · 23 junio',
      amount: 'S/ 420.00',
      icon: 'receipt',
      kind: 'expense',
      scope: 'trip',
      tone: 'expense',
      date: '2026-06-23',
    },
    {
      id: 'trip-2',
      title: 'Pasajes internos',
      subtitle: 'Transporte · 19 junio',
      amount: 'S/ 260.00',
      icon: 'plane',
      kind: 'expense',
      scope: 'trip',
      tone: 'expense',
      date: '2026-06-19',
    },
    {
      id: 'trip-3',
      title: 'Aporte inicial',
      subtitle: 'Fondo inicial · 10 junio',
      amount: 'S/ 1,500.00',
      icon: 'landmark',
      kind: 'initial',
      scope: 'trip',
      tone: 'info',
      date: '2026-06-10',
    },
    {
      id: 'trip-4',
      title: 'Aporte extra',
      subtitle: 'Ingreso · 12 junio',
      amount: 'S/ 1,300.00',
      icon: 'income',
      kind: 'income',
      scope: 'trip',
      tone: 'income',
      date: '2026-06-12',
    },
  ],
}

export const savingsSection: SavingsSection = {
  penBalance: 'S/ 8,200.00',
  usdBalance: '$ 1,240.00',
  goalName: 'Objetivo de ahorro',
  goalAmount: 'S/ 12,000.00',
  goalCurrent: 'S/ 8,200.00',
  goalRemaining: 'S/ 3,800.00',
  goalProgress: 68,
  progressLabel: '68% completado',
  balances: [
    {
      label: 'Ahorros en soles',
      amount: 'S/ 8,200.00',
      description: 'Meta principal',
      icon: 'piggy',
      tone: 'savings',
    },
    {
      label: 'Ahorros en dólares',
      amount: '$ 1,240.00',
      description: 'Reserva USD',
      icon: 'usd',
      tone: 'info',
    },
    {
      label: 'Objetivo',
      amount: 'S/ 12,000.00',
      description: '68% completado',
      icon: 'target',
      tone: 'savings',
    },
  ],
  history: [
    {
      id: 'savings-1',
      title: 'Depósito a meta',
      subtitle: 'PEN · 24 junio',
      amount: 'S/ 650.00',
      icon: 'piggy',
      kind: 'deposit',
      scope: 'savings',
      tone: 'savings',
      date: '2026-06-24',
    },
    {
      id: 'savings-2',
      title: 'Compra de dólares',
      subtitle: 'USD · 20 junio',
      amount: '$ 240.00',
      icon: 'usd',
      kind: 'deposit',
      scope: 'savings',
      tone: 'info',
      date: '2026-06-20',
    },
    {
      id: 'savings-3',
      title: 'Retiro puntual',
      subtitle: 'PEN · 11 junio',
      amount: 'S/ 120.00',
      icon: 'minus',
      kind: 'withdrawal',
      scope: 'savings',
      tone: 'expense',
      date: '2026-06-11',
    },
  ],
}

export const latestMovements: Movement[] = [
  personalSections.marcos.movements[0],
  personalSections.nayeli.movements[1],
  tripSection.latestExpenses[0],
  savingsSection.history[0],
  personalSections.marcos.movements[1],
]

export const summaryHighlights: BalanceSummary[] = [
  {
    label: 'Gastado hoy',
    amount: 'S/ 180.90',
    description: 'Consumo registrado hoy',
    icon: 'expense',
    tone: 'expense',
  },
  {
    label: 'Balance del mes',
    amount: 'S/ 4,209.10',
    description: 'Ingresos menos gastos',
    icon: 'equal',
    tone: 'income',
  },
  {
    label: 'Objetivo de ahorro',
    amount: '68%',
    description: 'S/ 8,200 de S/ 12,000',
    icon: 'target',
    tone: 'savings',
  },
]

export const categorySummaries: CategorySummary[] = [
  { label: 'Ingresos', amount: 'S/ 6,980.00', icon: 'income', tone: 'income' },
  { label: 'Gastos', amount: 'S/ 2,140.90', icon: 'expense', tone: 'expense' },
  { label: 'Viaje', amount: 'S/ 1,950.00', icon: 'plane', tone: 'info' },
  { label: 'Ahorro', amount: 'S/ 8,200.00', icon: 'piggy', tone: 'savings' },
]

export const sectionDetails: Record<AppSection, SectionDetail> = {
  summary: {
    title: 'Resumen',
    kicker: 'Panel principal',
    badge: 'Actualizado',
    heroLabel: 'Balance total',
    heroAmount: 'S/ 18,380.50',
    heroDescription: 'Saldos personales, viaje y ahorro en una sola vista.',
    icon: 'wallet',
    tone: 'info',
    actions: [],
  },
  marcos: {
    title: 'Marcos',
    kicker: 'Cuenta personal',
    badge: 'Ingresos',
    heroLabel: 'Saldo Marcos',
    heroAmount: 'S/ 4,820.00',
    heroDescription: 'Ingresos y gastos personales del mes.',
    icon: 'user',
    tone: 'income',
    actions: [
      { label: 'Ingreso', icon: 'income', tone: 'income' },
      { label: 'Gasto', icon: 'expense', tone: 'expense' },
    ],
  },
  nayeli: {
    title: 'Nayeli',
    kicker: 'Cuenta personal',
    badge: 'Gastos',
    heroLabel: 'Saldo Nayeli',
    heroAmount: 'S/ 3,410.50',
    heroDescription: 'Ingresos y gastos personales del mes.',
    icon: 'user',
    tone: 'expense',
    actions: [
      { label: 'Ingreso', icon: 'income', tone: 'income' },
      { label: 'Gasto', icon: 'expense', tone: 'expense' },
    ],
  },
  trip: {
    title: 'Viaje',
    kicker: 'Fondo compartido',
    badge: 'Plan',
    heroLabel: 'Saldo Viaje',
    heroAmount: 'S/ 1,950.00',
    heroDescription: 'Presupuesto reservado para próximos gastos.',
    icon: 'plane',
    tone: 'info',
    actions: [
      { label: 'Inicial', icon: 'landmark', tone: 'info' },
      { label: 'Gasto', icon: 'expense', tone: 'expense' },
    ],
  },
  savings: {
    title: 'Ahorros',
    kicker: 'Meta familiar',
    badge: 'Objetivo',
    heroLabel: 'Ahorros acumulados',
    heroAmount: 'S/ 8,200.00 · $ 1,240.00',
    heroDescription: 'Meta con saldos separados en soles y dólares.',
    icon: 'piggy',
    tone: 'savings',
    actions: [
      { label: 'Depósito', icon: 'piggy', tone: 'savings' },
      { label: 'Retiro', icon: 'expense', tone: 'expense' },
    ],
  },
  gym: {
    title: 'Gym',
    kicker: 'Asistencia',
    badge: 'Mensual',
    heroLabel: 'Calendario',
    heroAmount: 'Mes actual',
    heroDescription: 'Asistencia de Marcos y Nayeli al gimnasio.',
    icon: 'dumbbell',
    tone: 'info',
    actions: [],
  },
}
